version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: fastapi_app
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:80"
    volumes:
      - ./app:/app/app
      #- .:/app

    command: ["/app/.venv/bin/fastapi", "run", "app/main.py", "--port", "80", "--host", "0.0.0.0"]

volumes:
  postgres_data:
  #venv_data:
